import { Request, Response } from 'express';
import prisma from '../prisma';
import crypto from 'crypto';
import stream from 'stream';
import { sendEmail } from '../utils/email';

// ── Helper: generate invoice PDF buffer ──────────────────────────
async function generateInvoicePdf(order: any): Promise<Buffer> {
  let PDFDocument: any;
  try { PDFDocument = require('pdfkit'); } catch { throw new Error('pdfkit not installed'); }

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const buffers: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - 100;
    const lm = 50;
    const rm = doc.page.width - 50;

    // ── Header Bar ──
    doc.rect(0, 0, doc.page.width, 85).fill('#0B215E');
    doc.fill('#ffffff').fontSize(22).font('Helvetica-Bold').text('EQUIPSHARE', lm, 22);
    doc.fontSize(9).font('Helvetica').text('Smart Rental Marketplace', lm, 50);
    doc.fill('#ffffff').fontSize(8).font('Helvetica');
    doc.text('INVOICE', rm - 60, 22, { width: 60, align: 'right' });
    doc.text(`#${order.orderNumber}`, rm - 60, 34, { width: 60, align: 'right' });

    // ── Invoice Meta ──
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

    let y = 105;
    doc.fill('#0B215E').fontSize(10).font('Helvetica-Bold').text('Invoice Details', lm, y);
    y += 16;
    doc.fontSize(8.5).font('Helvetica');
    const leftMeta = [
      `Order Date: ${new Date(order.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`,
      `Invoice Date: ${dateStr}`,
      `Invoice Time: ${timeStr}`,
    ];
    const rn = order.renter;
    const renterName = rn ? `${rn.firstName || ''} ${rn.lastName || ''}`.trim() : '—';
    const ownerNames = [...new Set(order.items?.map((it: any) => {
      const o = it.equipment?.owner;
      return o ? `${o.firstName || ''} ${o.lastName || ''}`.trim() : null;
    }).filter(Boolean))];
    const rightMeta = [
      `Prepared by: EquipShare System`,
      `Generated by: ${ownerNames.length ? ownerNames.join(' & ') : renterName}`,
      `Status: Paid`,
    ];
    for (let i = 0; i < leftMeta.length; i++) {
      doc.fill('#555555').text(leftMeta[i], lm, y);
      doc.text(rightMeta[i], rm - 160, y, { width: 160, align: 'right' });
      y += 14;
    }

    // ── Bill To ──
    y += 8;
    doc.fill('#0B215E').fontSize(10).font('Helvetica-Bold').text('Bill To', lm, y);
    y += 15;
    doc.fill('#333333').fontSize(8.5).font('Helvetica')
      .text(renterName, lm, y)
      .text(`Email: ${rn?.email || '—'}`, lm, y + 12)
      .text(`Phone: ${rn?.phone || '—'}`, lm, y + 24);

    // ── Items Table Header ──
    y += 48;
    doc.rect(lm, y, rm - lm, 18).fill('#0B215E');
    doc.fill('#ffffff').fontSize(8).font('Helvetica-Bold');
    doc.text('Item', lm + 8, y + 4, { width: 170 });
    doc.text('Duration', lm + 178, y + 4, { width: 80 });
    doc.text('Rate', lm + 258, y + 4, { width: 70, align: 'right' });
    doc.text('Amount', lm + 328, y + 4, { width: 70, align: 'right' });

    // ── Items Table Rows ──
    y += 18;
    let ri = 0;
    for (const it of order.items) {
      const bg = ri % 2 === 0 ? '#f9f9f9' : '#ffffff';
      doc.rect(lm, y, rm - lm, 20).fill(bg);
      doc.fill('#333333').fontSize(7.5).font('Helvetica');
      doc.text((it.equipment?.title || '').substring(0, 30), lm + 8, y + 5, { width: 170 });
      doc.text(it.timeline || '—', lm + 178, y + 5, { width: 80 });
      doc.text(`Rwf ${Number(it.price ?? 0).toLocaleString()}`, lm + 258, y + 5, { width: 70, align: 'right' });
      doc.text(`Rwf ${Number(it.totalAmount ?? 0).toLocaleString()}`, lm + 328, y + 5, { width: 70, align: 'right' });
      y += 20;
      ri++;
    }

    // ── Totals ──
    y += 8;
    const itemsTotal = order.items?.reduce((s: number, it: any) => s + Number(it.totalAmount), 0) || 0;
    const displaySubtotal = order.subtotal || itemsTotal || order.totalAmount;
    const displayTax = order.tax || (order.subtotal ? 0 : itemsTotal * 0.18);
    const displayTotal = order.tax ? order.totalAmount : itemsTotal + itemsTotal * 0.18;
    const tx = rm - 180;
    const tw = 130;

    doc.fill('#555555').fontSize(8.5).font('Helvetica');
    doc.text('Subtotal', tx, y, { width: tw, align: 'right' });
    doc.text(`Rwf ${Number(displaySubtotal).toLocaleString()}`, tx + tw, y, { width: 50, align: 'right' });
    y += 16;

    doc.text('Tax (18%)', tx, y, { width: tw, align: 'right' });
    doc.text(`Rwf ${Number(displayTax).toLocaleString()}`, tx + tw, y, { width: 50, align: 'right' });
    y += 16;

    doc.moveTo(tx, y).lineTo(rm, y).stroke('#cccccc');
    y += 10;

    doc.fill('#0B215E').fontSize(12).font('Helvetica-Bold');
    doc.text('Total Paid (incl. tax)', tx, y, { width: tw, align: 'right' });
    doc.text(`Rwf ${Number(displayTotal).toLocaleString()}`, tx + tw, y, { width: 50, align: 'right' });

    // ── Footer ──
    y = doc.page.height - 65;
    doc.rect(0, y, doc.page.width, 65).fill('#0B215E');
    doc.fill('#ffffff').fontSize(7.5).font('Helvetica');
    doc.text('EquipShare — Smart Rental Marketplace | Thank you for your business!', lm, y + 14, { width: rm - lm, align: 'center' });
    doc.text(`Invoice #${order.orderNumber} | Generated on ${dateStr} at ${timeStr}`, lm, y + 28, { width: rm - lm, align: 'center' });
    doc.text('This is a computer-generated invoice.', lm, y + 42, { width: rm - lm, align: 'center' });

    doc.end();
  });
}

// ── Helper: send invoice email ───────────────────────────────────
async function sendInvoiceEmail(order: any) {
  const pdfBuffer = await generateInvoicePdf(order);
  const itemsHtml = order.items.map((it: any) =>
    `<tr><td style="padding:8px;border-bottom:1px solid #ddd">${it.equipment.title}</td><td style="padding:8px;border-bottom:1px solid #ddd">${it.timeline || '—'}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">Rwf ${Number(it.totalAmount).toLocaleString()}</td></tr>`
  ).join('');

  const subtotalVal = order.subtotal || order.totalAmount;
  const taxVal = order.tax || 0;

  const renterEmail = order.renter?.email || '—';
  const renterFirst = order.renter?.firstName || 'Customer';

  await sendEmail(
    renterEmail,
    `Invoice — EquipShare Order #${order.orderNumber}`,
    `<div style="font-family:sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#0B215E;padding:20px;text-align:center;border-radius:8px 8px 0 0">
        <h2 style="color:#ffffff;margin:0;font-size:22px">EQUIPSHARE</h2>
        <p style="color:#8899bb;margin:4px 0 0;font-size:12px">Smart Rental Marketplace</p>
      </div>
      <div style="padding:24px;border:1px solid #e0e0e0;border-top:none">
        <h2 style="color:#0B215E;margin:0 0 16px">Payment Confirmed</h2>
        <p style="color:#333;font-size:14px;margin:0 0 4px">Dear ${renterFirst},</p>
        <p style="color:#555;font-size:13px;margin:0 0 16px">Your payment for order <strong>#${order.orderNumber}</strong> was successful.</p>
        <table style="width:100%;border-collapse:collapse;margin:16px 0">
          <thead><tr style="background:#f5f5f5"><th style="padding:8px;text-align:left;font-size:12px;border-bottom:2px solid #ddd">Item</th><th style="padding:8px;text-align:left;font-size:12px;border-bottom:2px solid #ddd">Duration</th><th style="padding:8px;text-align:right;font-size:12px;border-bottom:2px solid #ddd">Amount</th></tr></thead>
          <tbody>${itemsHtml}</tbody>
        </table>
        <hr style="border:none;border-top:1px solid #e0e0e0;margin:12px 0" />
        <div style="text-align:right;font-size:14px">
          <p style="margin:4px 0;color:#555">Subtotal: <strong>Rwf ${Number(subtotalVal).toLocaleString()}</strong></p>
          <p style="margin:4px 0;color:#555">Tax (18%): <strong>Rwf ${Number(taxVal).toLocaleString()}</strong></p>
          <p style="margin:8px 0 0;font-size:18px;color:#0B215E;font-weight:bold">Total: Rwf ${Number(order.totalAmount).toLocaleString()}</p>
        </div>
        <p style="color:#333;font-size:13px;margin:20px 0 0">Your invoice PDF is attached.</p>
        <p style="color:#333;font-size:13px;margin:4px 0 0">Thank you for choosing EquipShare!</p>
      </div>
      <div style="background:#0B215E;padding:12px;text-align:center;border-radius:0 0 8px 8px">
        <p style="color:#8899bb;margin:0;font-size:10px">EquipShare — Smart Rental Marketplace</p>
      </div>
    </div>`,
    [{ filename: `invoice-order-${order.id}.pdf`, content: pdfBuffer }]
  );
}

export const initiatePayment = async (req: Request, res: Response) => {
  try {
    const { orderId } = req.body;
    const userId = (req as any).user?.id;
    const order = await prisma.order.findUnique({
      where: { id: Number(orderId) },
      include: { items: { include: { equipment: { include: { owner: true } } } }, renter: true },
    });
    if (!order) return res.status(404).json({ error: 'Order not found' });

    let payment = await prisma.payment.findUnique({ where: { orderId: order.id } });
    if (payment && payment.status === 'PAID') {
      return res.status(400).json({ error: 'This order has already been paid.' });
    }
    if (!payment) {
      payment = await prisma.payment.create({
        data: { amount: order.totalAmount, status: 'PAID', orderId: order.id, userId: userId || order.renterId },
      });
    } else {
      payment = await prisma.payment.update({ where: { id: payment.id }, data: { status: 'PAID' } });
    }

    await prisma.order.update({ where: { id: order.id }, data: { status: 'PROCESSING' } });

    const ownerIds = [...new Set(order.items.map((it: any) => it.equipment.ownerId))];
    for (const ownerId of ownerIds) {
      await prisma.notification.create({
        data: {
          userId: Number(ownerId),
          type: 'payment',
          title: 'New paid order',
          body: `Order ${order.orderNumber} was paid. Invoice available for download.`,
          read: false,
          linkUrl: `/owner/orders/${order.id}`,
        },
      });
    }

    sendInvoiceEmail(order).catch((err) => console.error('Failed to send invoice email:', err));

    return res.json({ success: true, message: 'Payment successful', paymentId: payment.id, orderId: order.id });
  } catch (error) {
    console.error('initiatePayment error', error);
    return res.status(500).json({ error: 'Failed to process payment' });
  }
};

// Webhook endpoint for PayPack payment events
export const paymentWebhook = async (req: Request, res: Response) => {
  try {
    const payload = req.body;
    console.log('[paymentWebhook] Received webhook:', JSON.stringify(payload, null, 2));

    // Extract payment/order information from various possible payload formats
    const status = payload?.data?.status || payload?.status || payload?.event;
    const meta = payload?.data?.meta || payload?.meta || {};
    const paymentId = meta.paymentId || payload?.data?.paymentId || payload?.paymentId;
    const orderId = meta.orderId || payload?.data?.orderId || payload?.orderId || payload?.order_id;

    console.log('[paymentWebhook] Status:', status, 'PaymentId:', paymentId, 'OrderId:', orderId);

    let payment = null;
    if (paymentId) {
      payment = await prisma.payment.findUnique({ where: { id: Number(paymentId) } });
    }
    if (!payment && orderId) {
      payment = await prisma.payment.findUnique({ where: { orderId: Number(orderId) } });
    }

    if (!payment) {
      console.warn('[paymentWebhook] Payment record not found for webhook');
      return res.json({ received: true });
    }

    // Normalize status and check if payment was successful
    const normalizedStatus = String(status).toLowerCase();
    const paidStatuses = ['successful', 'paid', 'completed', 'payment.completed', 'checkout.completed'];
    
    if (paidStatuses.includes(normalizedStatus)) {
      console.log('[paymentWebhook] Payment successful, updating payment and order status');
      
      await prisma.payment.update({ where: { id: payment.id }, data: { status: 'PAID' } });
      await prisma.order.update({ where: { id: payment.orderId }, data: { status: 'PROCESSING' } });

      const order = await prisma.order.findUnique({
        where: { id: payment.orderId },
        include: { items: { include: { equipment: true } }, renter: true },
      });
      
      if (order) {
        // Notify all equipment owners
        const owners = new Set<number>();
        for (const it of order.items) owners.add(it.equipment.ownerId);
        
        for (const ownerId of owners) {
          await prisma.notification.create({
            data: {
              userId: Number(ownerId),
              type: 'payment',
              title: 'New paid order',
              body: `Order ${order.orderNumber} was paid. Invoice available for download.`,
              read: false,
              linkUrl: `/owner/orders/${order.id}`,
            },
          });
        }

        // Send invoice email to renter (non-blocking)
        sendInvoiceEmail(order).catch((err) => console.error('[paymentWebhook] Failed to send invoice email:', err));
      }
    } else {
      console.log('[paymentWebhook] Payment status not successful, marking as PENDING');
      await prisma.payment.update({ where: { id: payment.id }, data: { status: 'PENDING' } });
    }

    return res.json({ received: true });
  } catch (error) {
    console.error('[paymentWebhook] ERROR:', error);
    return res.status(500).send('error');
  }
};

// ── Verify payment after redirect from PayPack ──────────────────────
export const verifyPayment = async (req: Request, res: Response) => {
  try {
    const orderId = Number(req.query.orderId || req.query.order_id || 0);
    const userId = (req as any).user?.id;

    console.log('[verifyPayment] Verifying payment for orderId:', orderId, 'userId:', userId);

    if (!orderId) {
      return res.status(400).json({ error: 'orderId is required' });
    }

    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: { renter: true, payment: true },
    });
    
    if (!order) {
      return res.status(404).json({ error: 'Order not found' });
    }
    
    if (order.renterId !== userId) {
      return res.status(403).json({ error: 'Forbidden' });
    }
    
    if (!order.payment) {
      return res.status(400).json({ error: 'No payment record found for this order' });
    }

    console.log('[verifyPayment] Payment status:', order.payment.status);
    return res.json({ success: true, paymentStatus: order.payment.status, orderId: order.id });
  } catch (error) {
    console.error('[verifyPayment] ERROR:', error);
    return res.status(500).json({ error: 'Verification failed' });
  }
};

// ── Download invoice PDF ───────────────────────────────────────────
export const getInvoice = async (req: Request, res: Response) => {
  try {
    const { orderId } = req.params;
    const userId = (req as any).user?.id;

    const order = await prisma.order.findUnique({
      where: { id: Number(orderId) },
      include: { items: { include: { equipment: true } }, renter: true },
    });
    if (!order) return res.status(404).json({ error: 'Order not found' });

    const isOwner = order.items.some((it: any) => it.equipment.ownerId === userId);
    if (order.renterId !== userId && !isOwner) {
      return res.status(403).json({ error: 'Forbidden' });
    }

    const pdfBuffer = await generateInvoicePdf(order);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-order-${order.id}.pdf`);
    res.end(pdfBuffer);
  } catch (error) {
    console.error('getInvoice error', error);
    res.status(500).json({ error: 'Failed to generate invoice' });
  }
};
